// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-section-wiki-head-text'
  | 'pref-apikey'
  | 'pref-baseurl'
  | 'pref-help'
  | 'pref-language'
  | 'pref-maxchars'
  | 'pref-model'
  | 'pref-provider'
  | 'pref-title'
  | 'pref-wikipath'
  | 'startup-begin'
  | 'startup-finish'
  | 'zoterowiki-export-complete'
  | 'zoterowiki-export-digest'
  | 'zoterowiki-export-latex'
  | 'zoterowiki-export-mindmap'
  | 'zoterowiki-export-notes'
  | 'zoterowiki-export-ppt'
  | 'zoterowiki-extract-methods'
  | 'zoterowiki-generate-collection'
  | 'zoterowiki-generate-selected'
  | 'zoterowiki-generating'
  | 'zoterowiki-menu-label'
  | 'zoterowiki-no-items-selected'
  | 'zoterowiki-sync-annotations'
  | 'zoterowiki-topic-research';
