// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apikey": string;
      "model": string;
      "baseurl": string;
      "wikipath": string;
      "maxchars": string;
      "language": string;
    };
  }
}
