/**
 * Obsidian Vault Writer — writes wiki pages to Obsidian vault
 * Uses Zotero file APIs (IOUtils + Zotero.File)
 */

import { WikiPage } from "../utils/types";
import { getPref } from "../utils/prefs";

export class ObsidianWriter {
  private basePath: string;

  constructor() {
    this.basePath = (getPref("wikipath") as string) || "";
    if (!this.basePath) {
      throw new Error(
        "Wiki output path not configured. Set it in Tools → Wiki Generator → Preferences",
      );
    }
  }

  /**
   * Write all wiki pages to the vault
   */
  async writePages(pages: WikiPage[]): Promise<void> {
    // Ensure directories exist
    for (const dir of ["entities", "concepts", "comparisons"]) {
      const dirPath = PathUtils.join(this.basePath, dir);
      try {
        await IOUtils.makeDirectory(dirPath);
      } catch (e: any) {
        // Directory may already exist
        if (e.name !== "NS_ERROR_FILE_ALREADY_EXISTS") {
          Zotero.debug(`[Wiki] mkdir error for ${dirPath}: ${e.message}`);
        }
      }
    }

    // Write each page
    for (const page of pages) {
      const subDir =
        page.type === "entity"
          ? "entities"
          : page.type === "concept"
            ? "concepts"
            : "comparisons";
      const filePath = PathUtils.join(this.basePath, subDir, page.filename);
      try {
        await Zotero.File.putContentsAsync(filePath, page.content);
        Zotero.debug(`[Wiki] Wrote: ${subDir}/${page.filename}`);
      } catch (e: any) {
        Zotero.debug(
          `[Wiki] Write error for ${filePath}: ${e.message}`,
        );
      }
    }
  }

  /**
   * Write/update the master index.md
   */
  async writeIndex(pages: WikiPage[]): Promise<void> {
    const now = new Date().toISOString().split("T")[0];
    const entities = pages.filter((p) => p.type === "entity");
    const concepts = pages.filter((p) => p.type === "concept");
    const comparisons = pages.filter((p) => p.type === "comparison");

    let md = `---\ntitle: Wiki Index\nupdated: ${now}\n---\n\n`;
    md += `# Wiki Index\n\n`;
    md += `> Generated by Zotero Wiki Generator\n> Last updated: ${now} | Total pages: ${pages.length}\n\n`;

    if (entities.length > 0) {
      md += `## 📄 Papers (${entities.length})\n`;
      for (const p of entities) {
        const title = this.extractTitle(p.content);
        md += `- [[${p.filename.replace(".md", "")}]] — ${title}\n`;
      }
      md += "\n";
    }

    if (concepts.length > 0) {
      md += `## 💡 Concepts (${concepts.length})\n`;
      for (const p of concepts) {
        const title = this.extractTitle(p.content);
        md += `- [[${p.filename.replace(".md", "")}]] — ${title}\n`;
      }
      md += "\n";
    }

    if (comparisons.length > 0) {
      md += `## ⚖️ Comparisons (${comparisons.length})\n`;
      for (const p of comparisons) {
        const title = this.extractTitle(p.content);
        md += `- [[${p.filename.replace(".md", "")}]] — ${title}\n`;
      }
      md += "\n";
    }

    const indexPath = PathUtils.join(this.basePath, "index.md");
    await Zotero.File.putContentsAsync(indexPath, md);
    Zotero.debug("[Wiki] Updated index.md");
  }

  /**
   * Append a log entry
   */
  async writeLog(
    message: string,
    details?: { pages: WikiPage[] },
  ): Promise<void> {
    const now = new Date();
    const timestamp = now.toISOString().replace("T", " ").slice(0, 16);
    let entry = `\n## [${timestamp}] ${message}\n`;

    if (details?.pages) {
      const entities = details.pages.filter((p) => p.type === "entity").length;
      const concepts = details.pages.filter((p) => p.type === "concept").length;
      const comparisons = details.pages.filter(
        (p) => p.type === "comparison",
      ).length;
      entry += `- Generated ${details.pages.length} pages: ${entities} entities, ${concepts} concepts, ${comparisons} comparisons\n`;
    }

    const logPath = PathUtils.join(this.basePath, "log.md");
    try {
      let existing = "";
      try {
        existing = String(await Zotero.File.getContentsAsync(logPath) || "");
      } catch {
        existing = `# Wiki Generation Log\n`;
      }
      await Zotero.File.putContentsAsync(logPath, existing + entry);
    } catch (e: any) {
      Zotero.debug(`[Wiki] Log write error: ${e.message}`);
    }
  }

  /**
   * Extract title from YAML frontmatter or first heading
   */
  private extractTitle(content: string): string {
    // Try YAML frontmatter title
    const yamlMatch = content.match(/^---\s*\n[\s\S]*?title:\s*["']?(.+?)["']?\s*\n/i);
    if (yamlMatch) return yamlMatch[1].trim().slice(0, 80);

    // Try first heading
    const headingMatch = content.match(/^#\s+(.+)$/m);
    if (headingMatch) return headingMatch[1].trim().slice(0, 80);

    return "Untitled";
  }
}
